### ISSUE TITLE
Off-by-one (or something like that) in GL

### ISSUE THREAD

**Issue by ckuethe** [biemster/rtl_waterfall#2]
![screenshot_2015-11-28_11-41-10](https://cloud.githubusercontent.com/assets/1131751/11453573/1cc21042-95c5-11e5-91ea-b8085881c9be.png)

looks like the buffer is rotated a few pixels: note that the top couple of rows are actually what the bottom of the screen should be. I'll see if I can't hunt down the cause of it..

**Comment by ckuethe** [comment]
That being said, I have all kinds of GPU artifacts on my system, so it's entirely possible that this is just a local problem

(surface pro 2, haswell GPU, xubuntu 15.10, linux 4.3)

**Comment by biemster** [comment]
Well spotted! Closing since it went in with the merge.
